version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./src:/var/www/html

  pgsql:
    image: postgres:latest
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      POSTGRES_USER: user
    ports:
      - 5051:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw
      
  php:
    container_name: php
    hostname: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:rw
